[riscv64-generic] Rebase on latest v6.1.106
lf-edge/eve-kernel pull request #134
Opened 2024-08-22 13:57 UTC by rouming

Just `git rebase v6.1.106`.

2024-08-23 04:35 UTC, rucoder approved these changes
LGTM. Approve to kick-off the build

2024-08-23 04:36 UTC, rucoder requested changes

2024-08-23 04:36 UTC, rucoder commented on .github/workflows/publish.yml
> +      - "eve-kernel-riscv64-v6.1.38-generic"
Change branch name!

2024-08-23 04:36 UTC, rucoder commented on .github/workflows/publish.yml
> +      - name: Build eve-kernel-riscv64
the same

2024-08-23 04:36 UTC, rucoder commented on .github/workflows/publish.yml
> +      - name: Push eve-kernel-riscv64-v6.1.38-generic if PR approved or pushed
the same

2024-08-28 07:40 UTC, rouming commented on .github/workflows/publish.yml
> +      - "eve-kernel-riscv64-v6.1.38-generic"
Done

2024-08-28 07:40 UTC, rouming commented on .github/workflows/publish.yml
> +      - name: Build eve-kernel-riscv64
Done

2024-08-28 07:40 UTC, rouming commented on .github/workflows/publish.yml
> +      - name: Push eve-kernel-riscv64-v6.1.38-generic if PR approved or pushed
Done

2024-08-28 10:43 UTC, rucoder approved these changes
LGTM

2024-08-28 15:07 UTC, merged