[amd64-generic] Rebase on latest v6.1.106
lf-edge/eve-kernel pull request #135
Opened 2024-08-22 14:00 UTC by rouming

Just `git rebase v6.1.106`, the following commit was dropped 
```
096014789d01 ("rsi91x: Check wowlan pointer in rsi_shutdown")
```

similar fix was applied in stable branch.

2024-08-23 04:30 UTC, rucoder commented
@rouming   DCO sometimes fails when rebasing. I think it should be ok to merge

2024-08-23 04:30 UTC, rucoder approved these changes
LGTM

2024-08-23 04:37 UTC, rucoder requested changes

2024-08-23 04:37 UTC, rucoder commented on .github/workflows/publish.yml
> +      - "eve-kernel-amd64-v6.1.38-generic"
branch name!

2024-08-23 04:37 UTC, rucoder commented on .github/workflows/publish.yml
> +  branch_name: "refs/heads/eve-kernel-amd64-v6.1.38-generic"
branch name!

2024-08-23 04:37 UTC, rucoder commented on .github/workflows/publish.yml
> +      - name: Push eve-kernel-amd64-v6.1.38-generic if PR approved or pushed
branch name!

2024-08-28 07:34 UTC, rouming commented on .github/workflows/publish.yml
> +      - "eve-kernel-amd64-v6.1.38-generic"
Done

2024-08-28 07:34 UTC, rouming commented on .github/workflows/publish.yml
> +      - name: Push eve-kernel-amd64-v6.1.38-generic if PR approved or pushed
Done

2024-08-28 07:34 UTC, rouming commented on .github/workflows/publish.yml
> +  branch_name: "refs/heads/eve-kernel-amd64-v6.1.38-generic"
Done

2024-08-28 10:43 UTC, rucoder approved these changes
LGTM

2024-08-28 15:07 UTC, merged