[WIP] Generate SBOM using buildkit's builtin mechanism
lf-edge/eve-kernel pull request #83
Opened 2024-02-27 23:55 UTC by rucoder

- `linuxkit cache push` is not implemented yet
- tested on a local eve build

2024-02-28 05:48 UTC, eriknordmark commented
DCO signoff is missing.

2024-02-28 07:51 UTC, rucoder commented
> DCO signoff is missing.

@eriknordmark it is not missing for this PR. There are 2 old commits with wrong sign-off string and I'm not sure what to do about it.

2024-02-28 08:05 UTC, eriknordmark commented
> @eriknordmark it is not missing for this PR. There are 2 old commits with wrong sign-off string and I'm not sure what to do about it.

That's odd. So the DCO checker is broken?
We can ignore it for now, but I wonder if we'll see the same issue for the same old commits for the next PR.

2024-02-28 08:56 UTC, deitch approved these changes
LGTM, except that `linuxkit cache push` is not yet implemented. Working on it. Real Soon Now ™️

2024-02-28 13:53 UTC, rucoder commented
tried `linuxkit cache push` from commit `54d9db8650400a9f6af72b176b64c6dcc30cba07`. It works but one last tiny fix is required. Right now it creates 2 tags assuming that eney image is multi-platform

2024-03-03 08:08 UTC, deitch approved these changes
LGTM.

Did you build it and do you see the correct sbom info? You should be able to look into the cache directly and see it.

2024-03-04 12:22 UTC, rucoder commented
@yash-zededa it seems we need to upgrade buildkit on github runner. https://github.com/lf-edge/eve-kernel/actions/runs/8128820721/job/22215156330?pr=83
```
docker buildx build \
--build-arg="SOURCE_DATE_EPOCH=1709322857" \
--build-arg="KBUILD_BUILD_TIMESTAMP=Fri Mar 1 19:54:17 2024 " \
--build-arg="LOCALVERSION=6c57bd876fea" \
--platform linux/amd64 -t lfedge/eve-kernel:merge-6c57bd876fea-gcc \
--sbom=true --output=type=oci,dest=/tmp/tmp.Fa2e4DNCy2-kernel.tar -f Dockerfile.gcc .
ERROR: attestations are not supported by the current buildkitd
make: *** [Makefile.eve:59: kernel-build-gcc] Error 1
```

2024-03-04 13:30 UTC, rucoder commented
> @yash-zededa it seems we need to upgrade buildkit on github runner. https://github.com/lf-edge/eve-kernel/actions/runs/8128820721/job/22215156330?pr=83
> 
> ```
> docker buildx build \
> --build-arg="SOURCE_DATE_EPOCH=1709322857" \
> --build-arg="KBUILD_BUILD_TIMESTAMP=Fri Mar 1 19:54:17 2024 " \
> --build-arg="LOCALVERSION=6c57bd876fea" \
> --platform linux/amd64 -t lfedge/eve-kernel:merge-6c57bd876fea-gcc \
> --sbom=true --output=type=oci,dest=/tmp/tmp.Fa2e4DNCy2-kernel.tar -f Dockerfile.gcc .
> ERROR: attestations are not supported by the current buildkitd
> make: *** [Makefile.eve:59: kernel-build-gcc] Error 1
> ```

nvm, we are running the latest buildkit anyway.

2024-03-04 13:30 UTC, deitch requested changes

2024-03-04 13:30 UTC, deitch commented on Makefile.eve
> +	docker builder inspect eve-kernel-builder || docker builder create --name eve-kernel-builder --driver docker-container --bootstrap
I recommend saving the builder to a Makefile var and using that here and in the build target

2024-03-04 13:30 UTC, deitch commented on Makefile.eve
> +	docker builder inspect eve-kernel-builder || docker builder create --name eve-kernel-builder --driver docker-container --bootstrap
I recommend redirecting the output of `inspect` to `/dev/null`, or it gets messy. You don't care about the output, only if it returns 0 or 1.

2024-03-04 13:30 UTC, deitch commented on Makefile.eve
> +	docker builder inspect eve-kernel-builder || docker builder create --name eve-kernel-builder --driver docker-container --bootstrap
Maybe an `@` at the beginning of the line?

2024-03-04 13:30 UTC, deitch commented on Makefile.eve
> +	--builder=eve-kernel-builder \
As above, use a var

2024-03-04 14:16 UTC, rucoder commented on Makefile.eve
> +	docker builder inspect eve-kernel-builder || docker builder create --name eve-kernel-builder --driver docker-container --bootstrap
> I recommend saving the builder to a Makefile var and using that here and in the build target

this was just a POC :). Will fix

2024-03-04 14:17 UTC, rucoder commented on Makefile.eve
> +	docker builder inspect eve-kernel-builder || docker builder create --name eve-kernel-builder --driver docker-container --bootstrap
> I recommend redirecting the output of `inspect` to `/dev/null`, or it gets messy. You don't care about the output, only if it returns 0 or 1.

it may be useful  to troubleshoot issues with CI/CD in future

2024-03-04 14:19 UTC, rucoder commented on Makefile.eve
> +	--builder=eve-kernel-builder \
@deitch should we fix a build-kit version to something like 0.12.5 ? I could name --builder eve-kernel-builder-$(BK_VERSION)

2024-03-04 14:23 UTC, deitch commented on Makefile.eve
> +	--builder=eve-kernel-builder \
Yeah, that is a good idea.

2024-03-04 15:03 UTC, rucoder commented
@deitch 
1. Please approve to rerun actions
2. `ocker buildx create` vs `docker builder create`. and possible problems here?

2024-03-04 15:07 UTC, deitch approved these changes

2024-03-04 21:39 UTC, rucoder commented
@deitch @rene @eriknordmark it seems all issues are now solved, we can merge this PR if there are no objections

2024-03-04 22:05 UTC, merged